spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_fase1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: desafio
    password: desafio
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

